C++ = c++
C++_FLAGS = -Wall -Wextra -Werror -std=c++98 -g3
INFILES = 	main.cpp Animal.cpp Dog.cpp Cat.cpp Brain.cpp
INCS = 	Animal.hpp Dog.hpp Cat.hpp Brain.hpp 

OBJFILES = $(INFILES:.cpp=.o)

NAME = Excute

all: $(NAME)

$(NAME):$(OBJFILES) $(INCS)
	$(C++) $(C++_FLAGS) $(OBJFILES) -o $(NAME) 

%.o: %.cpp
	$(C++) $(C++_FLAGS) -c $< -o $@

clean:
	rm -f $(OBJFILES)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re